### PR TITLE
use os.EOL instead of \n

### LINKED ISSUE #242: use os.EOL instead of \n
@blond I'll prepare a PR, but I need your advice.
Should we just replace `\n` with `EOL` or we have to introduce optional parameter for join string with `\n` as default for better reverse compatibility?

### PR DESCRIPTION
**Pull request by Guria**
resolves #242 
should I add any tests into PR?

### CODE REVIEW

**Comment by Guria** [comment]
rebased and made changes in test

**Comment by Guria** [comment]
@blond seems we have an issue. should we have separate reference files for apveyor for sample project, or we have a better way to solve it?

**Comment by blond** [comment]
@Guria Let's run `func-test` only in Travis. Need remove string [here](https://github.com/enb-make/enb/blob/master/appveyor.yml#L16).

**Comment by Guria** [comment]
Should I amend or make separate commit with meaningfull message?

**Comment by blond** [comment]
> Should I amend or make separate commit with meaningfull message?

Separate commit.

**Comment by Guria** [comment]
sorry bad rebase

**Comment by blond** [comment]
Thanks! :+1:

**Pull request merged**
